name: kool_todo
description: "Coolest Todo App created by one and only krd"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/svg/
    - assets/png/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
    - family: Quicksand
      fonts:
        - asset: fonts/quicksand/Quicksand-Regular.ttf
        - asset: fonts/quicksand/Quicksand-Bold.ttf
          weight: 700
        - asset: fonts/quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/quicksand/Quicksand-Light.ttf
          weight: 300

  uses-material-design: true